package nl.worldmorph.sim;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerLevel;
import nl.worldmorph.data.*;
import nl.worldmorph.npc.NpcManager;
public final class WorldMorphSimulation {
 private final EconomyManager economy=new EconomyManager(); private final DiplomacyManager diplomacy=new DiplomacyManager(); private final SettlementSimulator settlements=new SettlementSimulator(); private final KingdomSimulator kingdoms=new KingdomSimulator(); private final NpcManager npcs=new NpcManager();
 private final FamilyManager families=new FamilyManager(); private final ReputationManager reputation=new ReputationManager(); private final LawManager laws=new LawManager(); private final TradeManager trade=new TradeManager(); private final TechnologyManager technology=new TechnologyManager(); private final HistoryBook history=new HistoryBook(); private final SimulationBudget budget=new SimulationBudget(); private final NpcInteractionService interactions=new NpcInteractionService(); private final TreatyManager treaties=new TreatyManager(); private final JobManager jobs=new JobManager(); private final PersonalityEngine personalities=new PersonalityEngine(); private final MarketManager markets=new MarketManager(); private final WorldEventManager events=new WorldEventManager(); private final SettlementNeedsManager needs=new SettlementNeedsManager(); private final FactionManager factions=new FactionManager(); private final ConstructionPlanner construction=new ConstructionPlanner(); private final SuccessionManager succession=new SuccessionManager(); private final RebellionManager rebellion=new RebellionManager(); private final TerritoryManager territory=new TerritoryManager(); private final TaxManager taxes=new TaxManager(); private final SalaryManager salaries=new SalaryManager(); private final ElectionManager elections=new ElectionManager(); private final RelationshipManager relationships=new RelationshipManager(); private final MarriageManager marriages=new MarriageManager(); private final HousingManager housing=new HousingManager(); private final RoadNetwork roads=new RoadNetwork(); private final ImmigrationManager immigration=new ImmigrationManager(); private final PeaceNegotiationManager peace=new PeaceNegotiationManager(); private final QuestManager quests=new QuestManager(); private final EducationManager education=new EducationManager(); private final ResourceManager resources=new ResourceManager(); private final CouncilManager councils=new CouncilManager(); private final TradeRouteManager tradeRoutes=new TradeRouteManager(); private final CitizenMoodManager citizenMood=new CitizenMoodManager(); private final DiplomacyAI diplomacyAI=new DiplomacyAI(); private final CrimeManager crimes=new CrimeManager(); private final PrisonManager prisons=new PrisonManager(); private final NpcBubbleManager bubbles=new NpcBubbleManager(); private final HomeManager homes=new HomeManager(); private final SettlementNeedsSimulator needsSimulator=new SettlementNeedsSimulator(); private final NpcRoutineSimulator npcRoutines=new NpcRoutineSimulator(); private final PopulationSimulator population=new PopulationSimulator(); private final CivilizationExpansionManager expansion=new CivilizationExpansionManager(); private final Civilization100Manager civilization100=new Civilization100Manager(); private final DayOneArrivalManager dayOneArrival=new DayOneArrivalManager();
 private final WorldEventSimulator eventSimulator=new WorldEventSimulator(events,needs,economy);
 private ServerLevel loadedLevel;
 public void tick(MinecraftServer server){
  ServerLevel level=server.overworld();WorldMorphState state=WorldMorphStateAccess.get(level);NpcPersistentState npcState=NpcPersistentStateAccess.get(level);HomePersistentState homeState=HomePersistentStateAccess.get(level);NeedsPersistentState needsState=NeedsPersistentStateAccess.get(level);EconomyPersistentState economyState=level.getDataStorage().computeIfAbsent(EconomyPersistentState.TYPE);
  if(loadedLevel!=level){npcs.restore(npcState.all());homes.restore(homeState.all());needs.restore(needsState.all());economy.restore(economyState.all());loadedLevel=level;}
  state.tick();bubbles.tick(level,state.getSimulationTick());settlements.tick(state);kingdoms.tick(state);needsSimulator.tick(state,needs,citizenMood);npcs.simulate(state.getSimulationTick());npcRoutines.tick(state,npcs,needs,resources);population.tick(state,npcs,families,housing); civilization100.tick(state); dayOneArrival.tick(level,state); expansion.tick(level,state,npcs,families,relationships,marriages,jobs,resources,technology,territory,roads,housing); eventSimulator.tick(state);treaties.expire(state.getSimulationTick());
  if(state.getSimulationTick()%20==0){npcState.replaceAll(npcs.snapshots());homeState.replaceAll(homes.snapshots());needsState.replaceAll(needs.snapshots());economyState.replaceAll(economy.snapshots());}
  if(state.getSimulationTick()%200==0){economy.trade("wheat",100,100);}
  if(state.getSimulationTick()%1200==0){for(var k:java.util.List.copyOf(state.kingdoms().values())){int citizens=state.settlements().values().stream().filter(x->k.id().equals(x.kingdomId())).mapToInt(x->x.population()).sum();taxes.collect(state,k.id(),citizens);rebellion.resolve(state,k.id());}}
 }
 public EconomyManager economy(){return economy;} public DiplomacyManager diplomacy(){return diplomacy;} public NpcManager npcs(){return npcs;} public FamilyManager families(){return families;} public ReputationManager reputation(){return reputation;} public LawManager laws(){return laws;} public TradeManager trade(){return trade;} public TechnologyManager technology(){return technology;} public HistoryBook history(){return history;} public SimulationBudget budget(){return budget;} public NpcInteractionService interactions(){return interactions;} public TreatyManager treaties(){return treaties;} public JobManager jobs(){return jobs;} public PersonalityEngine personalities(){return personalities;} public MarketManager markets(){return markets;} public WorldEventManager events(){return events;} public WorldEventSimulator eventSimulator(){return eventSimulator;} public SettlementNeedsManager needs(){return needs;} public FactionManager factions(){return factions;} public ConstructionPlanner construction(){return construction;} public SuccessionManager succession(){return succession;} public TerritoryManager territory(){return territory;} public TaxManager taxes(){return taxes;} public SalaryManager salaries(){return salaries;} public ElectionManager elections(){return elections;} public RelationshipManager relationships(){return relationships;} public MarriageManager marriages(){return marriages;} public HousingManager housing(){return housing;} public RoadNetwork roads(){return roads;} public ImmigrationManager immigration(){return immigration;} public PeaceNegotiationManager peace(){return peace;} public QuestManager quests(){return quests;} public EducationManager education(){return education;} public ResourceManager resources(){return resources;} public CouncilManager councils(){return councils;} public TradeRouteManager tradeRoutes(){return tradeRoutes;} public CitizenMoodManager citizenMood(){return citizenMood;} public DiplomacyAI diplomacyAI(){return diplomacyAI;} public CrimeManager crimes(){return crimes;} public PrisonManager prisons(){return prisons;} public NpcBubbleManager bubbles(){return bubbles;} public HomeManager homes(){return homes;} public SettlementNeedsSimulator needsSimulator(){return needsSimulator;} public NpcRoutineSimulator npcRoutines(){return npcRoutines;} public PopulationSimulator population(){return population;} public CivilizationExpansionManager expansion(){return expansion;} public Civilization100Manager civilization100(){return civilization100;}
}